version: '3.8'
services:
  hass:
    container_name: hass
    image: "ghcr.io/home-assistant/raspberrypi2-homeassistant:2021.7.3"
    volumes:
      - ./ha_config:/config
      - ./lookin:/config/custom_components/lookin
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow
    ports:
      - 8123:8123
#    networks:
#      default:
#        ipv4_address: 192.168.88.100
    restart: always
    privileged: true
#    network_mode: host
