version: '3.8'
services:
  hass:
    container_name: hass
    image: "ghcr.io/home-assistant/raspberrypi2-homeassistant:2021.7.3"
    volumes:
      - ./ha_config:/config
      - ./lookin:/config/custom_components/lookin
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Moscow
#    ports:
#      - 8123:8123
#    networks:
#      default:
#        ipv4_address: 192.168.88.100
#    ports:
#      - "127.0.0.1:8123:8123"
    restart: always
    privileged: true
    network_mode: host

#networks:
#  default:
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.88.0/24
#          gateway: 192.168.88.1
#    driver_opts:
#      com.docker.network.driver.mtu: 1450
